Homework for Lesson 7 from Dalichuk
alex-pancho/aqa_py_290424 pull request #203
Opened 2024-09-03 11:09 UTC by AnnaDalichuk

2024-09-03 14:45 UTC, alex-pancho requested changes

2024-09-03 14:45 UTC, alex-pancho commented on lesson_07/Homework_07_Dalichuk.py
> +    return str_to_print
тут не дуже вдало використано while і функцію. По факту ви отримаєте лише останнє зі значень.
Якщо треба отримати всі (а ідея саме в цьому) то треба не str_to_print а якійсь dict_to_ ....

2024-09-03 14:45 UTC, alex-pancho commented on lesson_07/Homework_07_Dalichuk.py
> +    return print(f"The summ of {number1} and {number2} equals {number1+number2}.")
немає сенсу  return print, завжди буде None подумайте чому, я не раз пояснював

2024-09-04 21:19 UTC, AnnaDalichuk commented on lesson_07/Homework_07_Dalichuk.py
> +    return print(f"The summ of {number1} and {number2} equals {number1+number2}.")
точно, дякую, треба прибрати return:
def summ_function2(number1, number2):
    print(f"The summ of {number1} and {number2} equals {number1+number2}.")

2024-11-07 14:44 UTC, closed without merging