Додано домашку до лекції 8
alex-pancho/aqa_py_290424 pull request #64
Opened 2024-05-29 08:46 UTC by DanaIuich

Додано 2 вирішення до домашки 8 з використанням try/except

2024-05-29 09:01 UTC, alex-pancho requested changes

2024-05-29 09:01 UTC, alex-pancho commented on lesson_08/homework_08.py
> +            print(result)
```suggestion
            print(result)
```
помилка в тому, що як я не раз казав функція повинна щось ПОВЕРТАТИ. А у вас поверне None
Коротше підказка така: якщо це не функція для виводу або вводу -то в ній прінтів бути не повинно.

2024-05-29 09:01 UTC, alex-pancho commented on lesson_08/homework_08.py
> +find_sum_numbers(number_list)
В цілому подумайте, що буде, якщо данних буд 6 рядків, з невалідним занченням у 3, чи порахує ваша ф-ція щось післа 3 рядка?

2024-05-29 10:36 UTC, closed without merging

2024-05-30 12:00 UTC, DanaIuich commented on lesson_08/homework_08.py
> +find_sum_numbers(number_list)
Я додавала 4 рядок з валідним значенням. Функція все рахує

2024-05-30 12:01 UTC, DanaIuich commented on lesson_08/homework_08.py
> +            print(result)
Додала 3 рішення в новий пул реквест https://github.com/alex-pancho/aqa_py_290424/pull/67